### ISSUE TITLE
Set up CI for build and publish docker images to docker hub

### ISSUE THREAD

**Issue by zws33** [zws33/language-app#6]
```
name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    jobs:
      - name: Build and Publish Docker Image
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Build and push Docker image for App1
            if: ${{ contains(github.event_path, 'app1/') }}
            uses: docker/build-push-action@v2
            with:
              context: .
              file: ./app1/Dockerfile
              push: true
              tags: |
                your-dockerhub-username/app1:latest
                your-dockerhub-username/app1:${{ github.sha }}

          - name: Build and push Docker image for App2
            if: ${{ contains(github.event_path, 'app2/') }}
            uses: docker/build-push-action@v2
            with:
              context: .
              file: ./app2/Dockerfile
              push: true
              tags: |
                your-dockerhub-username/app2:latest
                your-dockerhub-username/app2:${{ github.sha }}
          # ... Repeat the above block for other apps if needed
```
